# Generated by Django 5.1.7 on 2025-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='value',
        ),
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
