# Generated by Django 5.1.7 on 2025-03-19 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0002_remove_todo_name_remove_todo_value_todo_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date must be in MM/DD/YYYY format.', regex='^(0[1-9]|1[0-2])/(0[1-9]|[12]\\d|3[01])/\\d{4}$')]),
        ),
    ]
